# Generated by Django 5.0.6 on 2024-05-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='hora',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='phone',
            new_name='telefone',
        ),
    ]
